#!bin/bash
USERID=$(id -u)
if [ $USERID -eq 0 ]
then 
echo " Error :: login sudo access"
exit 1 # other than 0
fi 
dnf install mqsql -y
if [ $? -ne 0 ]
then 
echo "installing MYSQL .. FAILURE"
exiit 1
else 
echo "installing MYSQL ... SUCCESS"
fi 
 
 dnf install git -y
 
 if [ $? -ne 0 ]
 then 
 echo "installing git ...FAILURE"
  exit 1
  elseecho "isntalling git ... SUCCESS"
  fi
